language: android
jdk: oraclejdk8
android:
  components:
    # The following 3 are needed to update the version of the SDK Travis provides.
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by the project
    - build-tools-27.0.1
    # The SDK version used to compile the project
    - android-27

#    # The emulator
#    - android-21

#    # System image for emulator during your tests
#    - sys-img-armeabi-v7a-android-21

before_install:
  - yes | sdkmanager "platforms;android-27"

#before_script:
# Emulator Management: Create, Start and Wait
#  # List available SDKs, emulators...
#  - android list targets
#  - android list sdk --no-ui --all --extended

#  # start an emulator
#  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  # Unlock the screen(?)
#  - adb shell input keyevent 82 &

script:
  - ./gradlew build test
#  - travis_wait 40 ./gradlew build connectedCheck

notifications:
  email: false
  slack: $SLACK_ACCOUNT:$SLACK_TOKEN#builds
