language: android
jdk: oraclejdk8
android:
  components:
    # The following 3 are needed to update the version of the SDK Travis provides.
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by the project
    - build-tools-27.0.2
    # The SDK version used to compile the project
    - android-27

    # The emulator
    - android-21

    # System image for emulator during your tests
    - sys-img-armeabi-v7a-android-21

# Emulator Management: Create, Start and Wait
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - travis_wait 40 ./gradlew build connectedCheck

notifications:
  email: false
  slack: $SLACK_ACCOUNT:$SLACK_TOKEN#builds
